# Generated by Django 6.0.3 on 2026-03-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='last_ai_match',
            field=models.JSONField(blank=True, help_text='Cached AI matching results', null=True),
        ),
    ]
