# Generated by Django 6.0.3 on 2026-03-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inquiry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_budget', models.DecimalField(decimal_places=2, help_text='Proposed cost (Rands)', max_digits=12)),
                ('proposal_text', models.TextField(help_text='Explain how you will reduce costs while maintaining quality')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('feedback', models.TextField(blank=True, help_text='Municipality feedback', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.professional')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bids/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.bid')),
            ],
        ),
    ]
